baseURL = "https://chroju.github.io/"
title = "the world as code"
metaDataFormat = "toml"
theme = "cactus"
canonifyURLs = true
summaryLength = 140
rssLimit = 10

hasCJKLanguage = true
languageCode = "ja"
enableEmoji = true

[author]
  name = "chroju"

[permalinks]
  post = "/blog/:year/:month/:day/:filename/"

[mediaTypes]
  [mediaTypes."application/rss"]
  basename = "atom.xml"

[params]
  name = "the world as code"
  description = "about IT Infrastructure, DevOps, and Hacker philosophy."
  bio = "Write code to automate everything !"
  socialIconStyle = "circle"
  copyright = "written by chroju"
  enableRSS = true

[social]
  githubalt = "https://github.com/chroju"
  twitter = "https://twitter.com/chroju"

