version: 2

jobs:
  checkout_code:
    docker:
      - image: circleci/golang:1.8
    working_directory: ~/hugo
    steps:
      - checkout
      - save_cache:
          key: hugo-cache-{{ epoch }}
          paths:
            - ~/hugo

  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: ~/hugo
    steps:
      - restore_cache:
          key: hugo-cache
      - run:
          command: |
            git submodule sync
            git submodule update --init
            go get github.com/gohugoio/hugo
            git clone https://github.com/chroju/chroju.github.io public
            rm -rf public/*
            hugo
      - save_cache:
          key: hugo-cache-public-{{ epoch }}
          paths:
            - ~/hugo/public

  deploy:
    machine:
      enabled: true
    working_directory: ~/hugo/public
    steps:
      - restore_cache:
          key: hugo-cache-public
      - run:
          command: |
            git config --global user.name chroju
            git config --global user.email chor.chroju@gmail.com
            git add --all
            git commit -m "${CIRCLE_BRANCH} (Circle CI)"
            git push git@github.com:chroju/chroju.github.io

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - deploy:
          requires:
            - build
