version: 2

jobs:
  checkout_code:
    docker:
      - image: circleci/golang:1.8
    working_directory: ~/hugo
    steps:
      - checkout
      - save_cache:
          key: hugo-cache
          paths:
            - ~/hugo

  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: ~/hugo
    steps:
      - restore_cache:
          key: hugo-cache-{{ .Branch }}
      - run:
          command: |
            git submodule sync
            git submodule update --init
            go get github.com/gohugoio/hugo
            hugo
      - save_cache:
          key: hugo-cache-{{ .Branch }}
          paths:
            - ~/hugo

  deploy:
    machine:
      enabled: true
    working_directory: ~/hugo
    steps:
      - restore_cache:
          key: hugo-cache-{{ .Branch }}
      - run:
          command: |
            cd public
            git config --global user.name chroju
            git config --global user.email chor.chroju@gmail.com
            git add --all
            git commit -m "${CIRCLE_BRANCH}"
            git push git@github.com:chroju/chroju.github.io

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
